spring.application.name=socialmedia

#server.servlet.contextPath=/api/v1
apiPrefix=${API_PREFIX}
#config database
###
spring.jpa.hibernate.ddl-auto=update
# change url when run docker container
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.CharSet=utf8mb4
spring.jpa.properties.hibernate.connection.collation=utf8mb4_0900_ai_ci
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
###

#config upload file
###
 #default = 1MB
spring.servlet.multipart.max-file-size=8MB

# #default = 10 MB (form data)
spring.servlet.multipart.max-request-size=80MB
###

#base-path
app.upload-file.base-uri=${UPLOAD_FILE_BASE_URI}

#config jwt
app.jwt.base64-secret=${JWT_SECRET}

#expiration :  15 minutes (900s)
app.jwt.access-token-validity-in-seconds=${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
# refresh token: 30 days (24*60*60*30 s)
app.jwt.refresh-token-validity-in-seconds=${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

management.endpoints.web.exposure.include=health,metrics


# websocket logging
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.web.socket.messaging=DEBUG


#oauth2 google login
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

default_avatar_url=https://res.cloudinary.com/dlz1eoryd/image/upload/v1750951984/3fc6f8d3-b8dd-4268-b0e7-2847f27f0455-defaultAvatar_yhnvrv.jpg

# configure mail server
# email dispatch flow: Spring server -> SMTP server (Gmail) -> client


# SMTP server
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
# app password for communications between servers
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# cloudinary setup
CLOUDINARY_URL=${CLOUDINARY_URL}

# redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=${REDIS_TIMEOUT}
spring.data.redis.password=${REDIS_PASSWORD}